require('keymaps')
require('globals')
require('packer_init')

require('plugins/cmp')
require('plugins/treesitter')
require('plugins/telescope')
require('plugins/lualine')
require('plugins/lazygit')
require('plugins/nvim-tree')
require('plugins/nvim-lsp-installer')
require('plugins/lspconfig')
require('plugins/null-ls')
